### ISSUE TITLE
iOS Blocks issue: settings for certain apps crash Settings.app

### ISSUE THREAD

**Issue by MarcMurphyGit** [ioscreatix/Peek-a-Boo#5]
Only the Weather settings panel is working (at least amongst the iOS Blocks supported apps). When selecting other apps‘ settings, the Settings app crashes.

**Comment by jonsparks** [comment]
On iOS 10 I had to manually install some of the blocks from https://packix.ioscreatix.com- no idea if the existing ones will still work though.

**Comment by MarcMurphyGit** [comment]
Can’t seem to find download buttons on his website?

**Comment by andrewwiik** [comment]
Please post this on the correct repository
